name: Build Webview for Windows

on: workflow_dispatch

jobs:

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      env: |
        - GOOS: "windows
        - GOARCH: "amd64"
        - CGO_ENABLED: "1"
      run: go build -ldflags '-H windowsgui' -o launcher.exe
        
    - name: Upload Build Artifact Windows
      uses: actions/upload-artifact@v2.3.1
      with:
        name: WindowsBuild
        path: launcher.exe
        if-no-files-found: error
        retention-days: 90
